/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_greenu_ptttalk_util_CodeUtils */

#ifndef _Included_com_witted_ptt_CodeUtils
#define _Included_com_witted_ptt_CodeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_greenu_ptttalk_util_CodeUtils
 * Method:    GetG729Ver
 * Signature: (I)Ljava/lang/String;


 */
JNIEXPORT jstring JNICALL Java_com_witted_ptt_CodeUtils_GetG729Ver
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_greenu_ptttalk_util_CodeUtils
 * Method:    G729ToLinear
 * Signature: ([BS[S)I
 */
JNIEXPORT jint JNICALL Java_com_witted_ptt_CodeUtils_G729ToLinear
  (JNIEnv *, jclass, jbyteArray, jshort, jshortArray);

/*
 * Class:     com_greenu_ptttalk_util_CodeUtils
 * Method:    LinearToG729
 * Signature: ([SS[B)I
 */
JNIEXPORT jint JNICALL Java_com_witted_ptt_CodeUtils_LinearToG729
  (JNIEnv *, jclass, jshortArray, jshort, jbyteArray);

/*
 * Class:     com_greenu_ptttalk_util_CodeUtils
 * Method:    G729Init
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_witted_ptt_CodeUtils_G729Init
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_greenu_ptttalk_util_CodeUtils
 * Method:    G929DeInit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_witted_ptt_CodeUtils_G929DeInit
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
